apiVersion: pdok.nl/v1alpha1
kind: OGCAPI
metadata:
  labels:
    app.kubernetes.io/name: ogcapi-operator
    app.kubernetes.io/managed-by: kustomize
  name: ogcapi-sample
spec:
  # TODO(user): Add fields here
